### ISSUE TITLE
Help Needed: docs/rules/index.md

### ISSUE THREAD

**Issue by molee1905** [smocean/eslint-zh#11]
[docs/rules/index.md](http://smocean.github.io/docs/rules/index)

They either prescribe a better way of doing something or help you avoid footguns.

**Comment by molee1905** [comment]
no-fallthrough - disallow fallthrough of case statements (recommended)

**Comment by cssmagic** [comment]
These are rules designed to prevent you from making mistakes. They either prescribe a better way of doing something or help you avoid footguns.

这些规则是为了阻止你踩坑。它们要么为你指明了更好的做事方法，要么可以帮助你绕开雷区。

**Comment by cssmagic** [comment]
已提 PR (#24)。

**Comment by molee1905** [comment]
非常感谢！@cssmagic
